"""added failed request queue model

Revision ID: 9238dfd8809f
Revises: 0ccfd12ed5d8
Create Date: 2019-03-28 11:56:20.501084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9238dfd8809f"
down_revision = "0ccfd12ed5d8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "failed_request_queue",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_", sa.DateTime(), nullable=False),
        sa.Column("api_name", sa.String(), nullable=False),
        sa.Column("path_to_module", sa.String(), nullable=False),
        sa.Column("call_args", sa.JSON(), nullable=True),
        sa.Column("fail_count", sa.Integer(), nullable=False),
        sa.Column("last_fail_time_", sa.DateTime(), nullable=False),
        sa.Column("last_fail_reason", sa.String(), nullable=False),
        sa.Column("hard_fail", sa.Boolean(), nullable=False),
        sa.Column("succeeded", sa.Boolean(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("identifier", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("type", "identifier"),
    )
    op.create_index(
        op.f("ix_failed_request_queue_hard_fail"),
        "failed_request_queue",
        ["hard_fail"],
        unique=False,
    )
    op.create_index(
        op.f("ix_failed_request_queue_last_fail_time_"),
        "failed_request_queue",
        ["last_fail_time_"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_failed_request_queue_last_fail_time_"),
        table_name="failed_request_queue",
    )
    op.drop_index(
        op.f("ix_failed_request_queue_hard_fail"), table_name="failed_request_queue"
    )
    op.drop_table("failed_request_queue")
    # ### end Alembic commands ###
